mwd/urls.py
from django.conf.urls import include,url
from django.contrib import admin
from django.views.generic.base import RedirectView

urlpatterns = [
	url(r'^$', RedirectView.as_view(url='/mwd/order/new', permanent=False), name='index'),
	url(r'^order/', include('order.urls', namespace="order")),
    url(r'^admin/', admin.site.urls)
]

order/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.new, name='new'),
    url(r'^new/$', views.new, name='new'),
    url(r'^login/$', views.login, name='login'),
    url(r'^(?P<customer_id>[0-9]+)/view/$', views.customer_view, name='customer_view'),
    url(r'^(?P<customer_id>[0-9]+)/(?P<ap_id>[0-9]+)/ap_update/$', views.ap_update, name='ap_update'),
    url(r'^(?P<customer_id>[0-9]+)/(?P<ap_id>[0-9]+)/ap_clear/$', views.ap_clear, name='ap_clear'),
    url(r'^(?P<customer_id>[0-9]+)/(?P<ap_id>[0-9]+)/ap_deploy/$', views.ap_deploy, name='ap_deploy'),
    url(r'^admin/$', views.admin, name='admin'),
    url(r'^admin/(?P<customer_id>[0-9]+)/update/$', views.admin_customer_update, name='admin_customer_update')
]

order/models.py
from django.db import models

# Create your models here.

class Customer(models.Model):
	name = models.CharField(max_length=200)
	email = models.CharField(max_length=200)
	password = models.CharField(max_length=200)
	ssid = models.CharField(max_length=200)
	portal_url = models.CharField(max_length=1000)
	aaa_ip = models.CharField(max_length=200)
	aaa_port = models.CharField(max_length=200)
	aaa_secret = models.CharField(max_length=200)
	wlc = models.CharField(max_length=200)
	pi_user = models.CharField(max_length=200,default="")
	pi_password = models.CharField(max_length=200,default="")
	gr_user = models.CharField(max_length=200,default="")
	gr_password = models.CharField(max_length=200,default="")
	gr_customer = models.CharField(max_length=200,default="")
	status = models.PositiveSmallIntegerField(default=0)
	
class AP(models.Model):
	customer = models.ForeignKey(Customer, on_delete=models.CASCADE)
	mac = models.CharField(max_length=200)
	name = models.CharField(max_length=200)
	status = models.PositiveSmallIntegerField(default=0)
	

order/views.py
from django.shortcuts import render

# Create your views here.

from django.http import HttpResponse, HttpResponseRedirect
from django.template import loader
from django.core.urlresolvers import reverse
from django.contrib import messages

from django.core.mail import send_mail

from .models import Customer
from .models import AP

from .mwapp import mwapp_sync_customer_status, mwapp_sync_ap_status, mwapp_deploy_ap_to_group, mwapp_get_wlc_list, mwapp_create_customer, mwapp_deploy_customer


def index(request):
	customer_list = Customer.objects.order_by('name')
	context = {
		'customer_list': customer_list,
	}
	return render(request, 'order/index.html', context)


def new(request):
	if request.method == 'POST' and request.POST:
		# Create new customer
		check_customer=Customer.objects.filter(email=request.POST['customer_email'])
		if len(check_customer) > 0:
			messages.error(request, 'Customer exists.')
			return HttpResponseRedirect(reverse('order:new'))
		mwapp_create_customer(request.POST['customer_name'],request.POST['customer_email'],request.POST['customer_ssid'],request.POST['customer_aps'])
		request.session["admin"] = 0
		request.session["email"] = request.POST['customer_email']
		return HttpResponseRedirect(reverse('order:customer_view', args=(new_customer.pk,)))
	else:
		request.session["admin"] = 0
		request.session["email"] = ""
		return render(request, 'order/new.html')
		
def login(request):
	if request.POST['customer_email'] == "admin":
		request.session["admin"] = 1
		return HttpResponseRedirect(reverse('order:admin'))
	customer=Customer.objects.filter(email=request.POST['customer_email'])
	if len(customer) == 0:
		messages.error(request, 'Customer unknown.')
		return HttpResponseRedirect(reverse('order:new'))
	else:
		request.session["admin"] = 0
		request.session["email"] = request.POST['customer_email']
		return HttpResponseRedirect(reverse('order:customer_view', args=(customer[0].pk,)))
    
def customer_view(request, customer_id):
	customer = Customer.objects.get(pk=customer_id)
	if customer.email != request.session["email"]:
		if request.session["admin"] == 0:
			return HttpResponseRedirect(reverse('order:new'))
	
	customer_aps = AP.objects.filter(customer=customer)
	
	mwapp_sync_customer_status(customer)
	
	for ap in customer_aps:
		mwapp_sync_ap_status(ap)				
	
	context = {
		'customer': customer,
		'customer_aps': customer_aps,
	}
	return render(request, 'order/view.html', context)
	
def ap_update(request, customer_id, ap_id):
	change_ap = AP.objects.get(pk=ap_id)
	change_ap.status = 0
	change_ap.mac = request.POST['ap_mac']
	change_ap.save()
	return HttpResponseRedirect(reverse('order:customer_view', args=(customer_id,)))
	
def ap_clear(request, customer_id, ap_id):
	change_ap = AP.objects.get(pk=ap_id)
	change_ap.status = 0
	change_ap.mac = ""
	change_ap.save()
	return HttpResponseRedirect(reverse('order:customer_view', args=(customer_id,)))
	
def ap_deploy(request, customer_id, ap_id):
	deploy_ap = AP.objects.get(pk=ap_id)
	mwapp_deploy_ap_to_group(deploy_ap)
	return HttpResponseRedirect(reverse('order:customer_view', args=(customer_id,)))
	
def admin(request):
	customers = Customer.objects.all()
	wlc_list = mwapp_get_wlc_list()
	#raise Exception(wlc_list)
	
	for customer in customers:
		mwapp_sync_customer_status(customer)
	
	customers = customers.order_by('status')
	
	customers_with_wlcs = []
	for customer in customers:
		customer_with_list={
			'pk':customer.pk,
			'name':customer.name,
			'email':customer.email,
			'status':customer.status,
			'ssid':customer.ssid,
			'wlc':customer.wlc,		
			'portal_url':customer.portal_url,
			'aaa_ip':customer.aaa_ip,
			'aaa_port':customer.aaa_port,
			'aaa_secret':customer.aaa_secret,
			'wlc_list':[],
			'pi_user':customer.pi_user,
			'pi_password':customer.pi_password,
			'gr_user':customer.gr_user,
			'gr_password':customer.gr_password,
			'gr_customer':customer.gr_customer,
			}
		selected=0
		for wlc_check in wlc_list:
			if wlc_check['ip'] == customer.wlc:
				customer_with_list['wlc_list'].append({"name":wlc_check['name'],"ip":wlc_check['ip'],"selected":"1"})
				selected=1
			else:
				customer_with_list['wlc_list'].append({"name":wlc_check['name'],"ip":wlc_check['ip'],"selected":"0"})
		if selected==0:
			customer_with_list['wlc_list'].append({"name":customer.wlc,"ip":customer.wlc,"selected":"1"})
		customers_with_wlcs.append(customer_with_list)
	context = {
		'customers': customers_with_wlcs
	}
	return render(request, 'order/admin.html', context)
	
def admin_customer_update(request, customer_id):
	if 'update' in request.POST:
		change_customer = Customer.objects.get(pk=customer_id)
		change_customer.wlc=request.POST['wlc']
		change_customer.portal_url=request.POST['portal_url']
		change_customer.aaa_ip=request.POST['aaa_ip']
		change_customer.aaa_secret=request.POST['aaa_secret']
		change_customer.pi_user=request.POST['pi_user']
		change_customer.pi_password=request.POST['pi_password']
		change_customer.gr_user=request.POST['gr_user']
		change_customer.gr_password=request.POST['gr_password']
		change_customer.gr_customer=request.POST['gr_customer']
		change_customer.save()
	elif 'delete' in request.POST:
		delete_customer = Customer.objects.get(pk=customer_id)
		delete_customer.delete()
	else:
		deploy_customer = Customer.objects.get(pk=customer_id)
		mwapp_deploy_customer(deploy_customer)
		#deploy_cli_template("AP to APGroup",{"aa": "bbb", "cc": "ddd"},request.POST['wlc'])
	return HttpResponseRedirect(reverse('order:admin'))
	
	
	
	
	

order/templates/order/admin.html
{% load staticfiles %}

<link rel="stylesheet" href="{% static 'style.css' %}" />
<link rel="stylesheet" href="{% static 'admin-style.css' %}" />

<div class="admin_header">
<div class="admin_logo">
</div>
<div class="admin_title"><h1>Managed WiFi Admin Dashboard</h1></div>
</div>
<div class="admin_top"></div>

<TABLE class="admintable" border=1px>
<TR><TH>Customer</TH><TH>Status</TH><TH>SSID</TH><TH>WLC</TH><!--<TH>Portal URL</TH>--><TH>AAA Server</TH><TH>GlobalReach Credentials</TH><TH>Prime Infrastructure Credentials</TH>
<TH></TH><TH></TH><TH></TH></TR>
{% for customer in customers %}
<TR>
<FORM method=POST action='{% url "order:admin_customer_update" customer.pk %}'>
{% csrf_token %}
<TD class="customer_name_td">
<TABLE class='sub_table' width="100%">
<TR><TD class='sub_table_input'>{{ customer.name }}</TD></TR>
<TR><TD class='sub_table_input'>E-Mail: {{ customer.email }}</TD></TR>
</TABLE>
</TD>
<TD class="customer_status_td_{{ customer.status }}"><div class="customer_status_value">{{ customer.status }}</div></TD>
<TD>{{ customer.ssid }}</TD>
<TD>
{% if customer.status < 2 %}
	<SELECT name="wlc">
		{% for wlc in customer.wlc_list %}
			<OPTION value='{{ wlc.ip }}' 
			{% if wlc.selected == "1" %}
				selected
			{% endif %}
			>{{ wlc.name }}</OPTION>
 		{% endfor %}
	</SELECT>
{% else %}
	{% for wlc in customer.wlc_list %}
		{% if wlc.ip == customer.wlc %}
			{{ wlc.name }}
		{% endif %}
	{% endfor %}
{% endif %}
</TD>
<!--<TD><INPUT name='portal_url' type=text value='{{ customer.portal_url }}'></TD>-->
<TD>
<TABLE class='sub_table'>
<TR><TD class='sub_table_label'>Index:</TD><TD class='sub_table_input'><INPUT name='aaa_ip' type=text value='{{ customer.aaa_ip }}'></TD></TR>
<!-- <TR><TD class='sub_table_label'>Port:</TD><TD class='sub_table_input'><INPUT name='aaa_port' type=text value='{{ customer.aaa_port }}'></TD></TR>
<TR><TD class='sub_table_label'>Secret:</TD><TD class='sub_table_input'><INPUT name='aaa_secret' type=text value='{{ customer.aaa_secret }}'></TD></TR>
-->
</TABLE>
</TD>
<TD>
<TABLE class='sub_table'>
<TR><TD class='sub_table_label'>Username:</TD><TD class='sub_table_input'><INPUT name='gr_user' type=text value='{{ customer.gr_user }}'></TD></TR>
<TR><TD class='sub_table_label'>Password:</TD><TD class='sub_table_input'><INPUT name='gr_password' type=text value='{{ customer.gr_password }}'></TD></TR>
<TR><TD class='sub_table_label'>CustomerID:</TD><TD class='sub_table_input'><INPUT name='gr_customer' type=text value='{{ customer.gr_customer }}'></TD></TR>
</TABLE>
</TD>
<TD>
<TABLE class='sub_table'>
<TR><TD class='sub_table_label'>Username:</TD><TD class='sub_table_input'><INPUT name='pi_user' type=text value='{{ customer.pi_user }}'></TD></TR>
<TR><TD class='sub_table_label'>Password:</TD><TD class='sub_table_input'><INPUT name='pi_password' type=text value='{{ customer.pi_password }}'></TD></TR>
</TABLE>
</TD>
<TD>
{% if customer.status < 2 %}
<INPUT name='update' type=submit value="Update"></TD>
{% endif %}
{% if customer.status = 0 %}
<TD></TD>
{% endif %}
{% if customer.status = 1 %}
<TD><INPUT name='deploy' type=submit value="Deploy"></TD>
{% endif %}
{% if customer.status = 2 %}
<TD><INPUT name='undeploy' type=submit value="Un-Deploy"></TD><TD></TD>
{% endif %}
{% if customer.status < 2 %}
<TD><INPUT name='delete' type=submit value="Delete"></TD>
{% endif %}
</FORM>
</TR>
{% endfor %}
</TABLE>

order/templates/order/index.html
<BUTTON onClick="location.href='new/'">New</BUTTON>

order/templates/order/new.html
{% load staticfiles %}

<link rel="stylesheet" href="{% static 'style.css' %}" />

{% if messages %}
<ul class="messages">
    {% for message in messages %}
    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
    {% endfor %}
</ul>
{% endif %}

<div class="new_customer_form">
<form action="{% url 'order:new' %}" method="post">

{% csrf_token %}

Customer name: <INPUT type=text name="customer_name"></INPUT><BR>
Email: <INPUT type=text name="customer_email"></INPUT><BR>

Number of APs: <INPUT type=number name="customer_aps" value=0></INPUT><BR>
SSID: <INPUT type=text name="customer_ssid"></INPUT><BR>

<INPUT value="Order" type=submit></INPUT>
</form>
</div>

<div class="login_form">
<form action="{% url 'order:login' %}" method="post">
{% csrf_token %}

Email: <INPUT type=text name="customer_email"></INPUT><BR>
<INPUT value="Login" type=submit></INPUT>
</form>
</div>

order/templates/order/view.html
{% load staticfiles %}

<link rel="stylesheet" href="{% static 'style.css' %}" />
<link rel="stylesheet" href="{% static 'customer-style.css' %}" />

<div class="customer_view_header">
<div class="customer_view_logo"></div>
<div class="customer_view_title"><h1>{{ customer.name }}'s Dashboard</h1></div>
</div>

{% if customer.status == 2 %}
	SSID: {{ customer.ssid }}
	<BR>
	Portal URL: {{ customer.portal_url }}
	<BR>
	AAA: {{ customer.aaa_ip }}
	<BR>
	AAA Secret: {{ customer.aaa_secret }}
	<BR>
	Staus: {{ customer.status }}
	<BR>
	Assigned WLC: {{ customer.wlc }}
	<TABLE>
	{% for ap in customer_aps %}
		<TR>
		{% if ap.status == 0 %}
		<FORM method=POST action='{% url "order:ap_update" customer.pk ap.pk %}'>
		{% csrf_token %}
		<TD>
		<INPUT type=hidden name=ap_id value='{{ ap.pk }}'>
		<INPUT type=text name='ap_mac' value='{{ ap.mac }}'>
		</TD>
		<TD bgcolor=#ff0000 width=10px></TD>
		<TD><INPUT type=submit value="Add MAC"></TD>
		</FORM>
		{% elif ap.status == 1 %}
		<FORM method=POST action='{% url "order:ap_clear" customer.pk ap.pk %}'>
		{% csrf_token %}
		<TD>
		{{ ap.mac }}
		</TD>
		<TD bgcolor=#ff8800 width=10px></TD>
		<TD>
		<INPUT type=hidden name=ap_id value='{{ ap.pk }}'>
		<INPUT type=submit value="Clear MAC">
		</TD>
		</FORM>
		{% elif ap.status == 2 %}
		<FORM method=POST action='{% url "order:ap_clear" customer.pk ap.pk %}'>
		{% csrf_token %}
		<TD>
		{{ ap.mac }}
		</TD>
		<TD bgcolor=#ffff00 width=10px></TD>
		<TD>
		<INPUT type=hidden name=ap_id value='{{ ap.pk }}'>
		<INPUT type=submit value="Clear MAC">
		</TD>
		</FORM>
		<FORM method=POST action='{% url "order:ap_deploy" customer.pk ap.pk %}'>
		{% csrf_token %}
		<TD>
		<INPUT type=hidden name=ap_id value='{{ ap.pk }}'>
		<INPUT type=submit value="Deploy">
		</TD>
		</FORM>
		{% elif ap.status == 3 %}
		<FORM method=POST action='{% url "order:ap_clear" customer.pk ap.pk %}'>
		{% csrf_token %}
		<TD>
		{{ ap.mac }}
		</TD>
		<TD bgcolor=#00ff00 width=10px></TD>
		<TD>
		<INPUT type=hidden name=ap_id value='{{ ap.pk }}'>
		<INPUT type=submit value="Clear MAC">
		</TD>
		</FORM>
		{% endif %}
		</TR>
	{% endfor %}
	</TABLE>
{% else %}
    Deployment in process
{% endif %}